module.exports = [
  {
    pageName: "index",
    metaDataPageDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue turpis id tellus vestibulum, sit amet vulputate ante finibus. Aenean lacinia nisl sapien, ut molestie sapien elementum sed. In fringilla aliquam tortor, quis lobortis purus sollicitudin quis. In hac habitasse platea dictumst. Nullam congue tempus sapien ut laoreet. Donec quis odio eget lacus dictum pulvinar. Aliquam iaculis odio nec nibh hendrerit posuere. Nunc nec commodo sem, et faucibus libero.`,
    templatePage: "1_index.njk",
    outputHTML: "index.html",
    outputCSS: "1_index.css",
    pageSections: ["02_Carousel", "04_About", "06_Staff", "07_Updates"],
    banner_superscript: `Welcome to`,
    banner_header: `The Hill Preparatory School`,
    banner_subscript: `We believe in holistic child development that turns every student into an active global citizen.`,
  },
  {
    pageName: "about",
    metaDataPageDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue turpis id tellus vestibulum, sit amet vulputate ante finibus. Aenean lacinia nisl sapien, ut molestie sapien elementum sed. In fringilla aliquam tortor, quis lobortis purus sollicitudin quis. In hac habitasse platea dictumst. Nullam congue tempus sapien ut laoreet. Donec quis odio eget lacus dictum pulvinar. Aliquam iaculis odio nec nibh hendrerit posuere. Nunc nec commodo sem, et faucibus libero.`,
    templatePage: "2_about.njk",
    outputHTML: "about.html",
    outputCSS: "2_about.css",
    pageSections: [],
    banner_superscript: `Welcome to`,
    banner_header: `The Hill Preparatory School`,
    banner_subscript: `We believe in holistic child development that turns every student into an active global citizen.`,
  },
  {
    pageName: "curriculum",
    metaDataPageDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue turpis id tellus vestibulum, sit amet vulputate ante finibus. Aenean lacinia nisl sapien, ut molestie sapien elementum sed. In fringilla aliquam tortor, quis lobortis purus sollicitudin quis. In hac habitasse platea dictumst. Nullam congue tempus sapien ut laoreet. Donec quis odio eget lacus dictum pulvinar. Aliquam iaculis odio nec nibh hendrerit posuere. Nunc nec commodo sem, et faucibus libero.`,
    templatePage: "3_curriculum.njk",
    outputHTML: "curriculum.html",
    outputCSS: "3_curriculum.css",
    pageSections: ["12_Subjects"],
    banner_superscript: `Welcome to`,
    banner_header: `The Hill Preparatory School`,
    banner_subscript: `We believe in holistic child development that turns every student into an active global citizen.`,
  },
  {
    pageName: "staff",
    metaDataPageDescription: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue turpis id tellus vestibulum, sit amet vulputate ante finibus. Aenean lacinia nisl sapien, ut molestie sapien elementum sed. In fringilla aliquam tortor, quis lobortis purus sollicitudin quis. In hac habitasse platea dictumst. Nullam congue tempus sapien ut laoreet. Donec quis odio eget lacus dictum pulvinar. Aliquam iaculis odio nec nibh hendrerit posuere. Nunc nec commodo sem, et faucibus libero.`,
    templatePage: "4_staff.njk",
    outputHTML: "staff.html",
    outputCSS: "4_staff.css",
    pageSections: ["06_Staff"],
    banner_superscript: `Welcome to`,
    banner_header: `The Hill Preparatory School`,
    banner_subscript: `We believe in holistic child development that turns every student into an active global citizen.`,
  },
];
