module.exports = [
  {
    sectionTitle: "Navigation section",
    sectionSrcPathArray: ["03_HTML/01_Navbar/"],
    sectionIncludedTemplateString: "01_Navbar.njk",
    sectionOutputFileName: "01_Navbar.html",
    cssFilePath: "../01_CSS/01_Navbar",
    cssFilesArray: [
      "01_Navbar",
      "01_Navbar_Hamburger",
      "01_Navbar_media_queries",
    ],
  },
  {
    sectionTitle: "Carousel section",
    sectionSrcPathArray: ["03_HTML/02_Carousel/"],
    sectionIncludedTemplateString: "02_Carousel.njk",
    sectionOutputFileName: "02_Carousel.html",
    cssFilePath: "../01_CSS/02_Carousel",
    cssFilesArray: ["02_Carousel", "02_Carousel_media_queries"],
  },
  // {
  //   sectionTitle: "Cells section",
  //   sectionSrcPathArray: ["03_HTML/03_Cells/", "03_HTML/03_Cells/icons"],
  //   sectionIncludedTemplateString: "03_Cells.njk",
  //   sectionOutputFileName: "03_Cells.html",
  //   cssFilePath: "../01_CSS/03_Cells",
  //   cssFilesArray: ["03_Cells", "03_Cells_media_queries"],
  // },
  {
    sectionTitle: "About section",
    sectionSrcPathArray: ["03_HTML/04_About/"],
    sectionIncludedTemplateString: "04_About.njk",
    sectionOutputFileName: "04_About.html",
    cssFilePath: "../01_CSS/04_About",
    cssFilesArray: ["04_About", "04_About_media_queries"],
  },
  // {
  //   sectionTitle: "Testimonials section",
  //   sectionSrcPathArray: ["03_HTML/05_Testimonials/"],
  //   sectionIncludedTemplateString: "05_Testimonials.njk",
  //   sectionOutputFileName: "05_Testimonials.html",
  //   cssFilePath: "../01_CSS/05_Testimonials",
  //   cssFilesArray: ["05_Testimonials", "05_Testimonials_media_queries"],
  // },
  {
    sectionTitle: "Staff section",
    sectionSrcPathArray: ["03_HTML/06_Staff/"],
    sectionIncludedTemplateString: "06_Staff.njk",
    sectionOutputFileName: "06_Staff.html",
    cssFilePath: "../01_CSS/06_Staff",
    cssFilesArray: ["06_Staff", "06_Staff_media_queries"],
  },
  {
    sectionTitle: "Updates section",
    sectionSrcPathArray: ["03_HTML/07_Updates/"],
    sectionIncludedTemplateString: "07_Updates.njk",
    sectionOutputFileName: "07_Updates.html",
    cssFilePath: "../01_CSS/07_Updates",
    cssFilesArray: ["07_Updates", "07_Updates_media_queries"],
  },
  {
    sectionTitle: "Footer section",
    sectionSrcPathArray: ["03_HTML/08_Footer/"],
    sectionIncludedTemplateString: "08_Footer.njk",
    sectionOutputFileName: "08_Footer.html",
    cssFilePath: "../01_CSS/08_Footer",
    cssFilesArray: ["08_Footer", "08_Footer_media_queries"],
  },
  {
    sectionTitle: "Welcome section",
    sectionSrcPathArray: ["03_HTML/09_Welcome/"],
    sectionIncludedTemplateString: "09_Welcome.njk",
    sectionOutputFileName: "09_Welcome.html",
    cssFilePath: "../01_CSS/09_Welcome",
    cssFilesArray: ["09_Welcome", "09_Welcome_media_queries"],
  },
  {
    sectionTitle: "Video curriculum section",
    sectionSrcPathArray: ["03_HTML/10_Video_Curriculum/"],
    sectionIncludedTemplateString: "10_Video_Curriculum.njk",
    sectionOutputFileName: "10_Video_Curriculum.html",
    cssFilePath: "../01_CSS/10_Video",
    cssFilesArray: ["10_Video", "10_Video_media_queries"],
  },
];
