module.exports = [
  {
    sectionTitle: "Navigation section",
    sectionSrcPathArray: ["03_HTML/01_Navbar/"],
    sectionIncludedTemplateString: "01_Navbar.njk",
    sectionOutputFileName: "01_Navbar.html",
    cssFilePath: "../01_CSS/01_Navbar",
    cssFilesArray: ["01_Navbar"],
  },
  {
    sectionTitle: "Carousel section",
    sectionSrcPathArray: ["03_HTML/02_Carousel/"],
    sectionIncludedTemplateString: "02_Carousel.njk",
    sectionOutputFileName: "02_Carousel.html",
    cssFilePath: "../01_CSS/02_Carousel",
    cssFilesArray: ["02_Carousel"],
  },
  {
    sectionTitle: "Cells section",
    sectionSrcPathArray: ["03_HTML/03_Cells/", "03_HTML/03_Cells/icons"],
    sectionIncludedTemplateString: "03_Cells.njk",
    sectionOutputFileName: "03_Cells.html",
    cssFilePath: "../01_CSS/03_Cells",
    cssFilesArray: ["03_Cells"],
  },
  {
    sectionTitle: "About section",
    sectionSrcPathArray: ["03_HTML/04_About/"],
    sectionIncludedTemplateString: "04_About.njk",
    sectionOutputFileName: "04_About.html",
    cssFilePath: "../01_CSS/04_About",
    cssFilesArray: ["04_About"],
  },
  {
    sectionTitle: "Testimonials section",
    sectionSrcPathArray: ["03_HTML/05_Testimonials/"],
    sectionIncludedTemplateString: "05_Testimonials.njk",
    sectionOutputFileName: "05_Testimonials.html",
    cssFilePath: "../01_CSS/05_Testimonials",
    cssFilesArray: ["05_Testimonials"],
  },
  {
    sectionTitle: "Staff section",
    sectionSrcPathArray: ["03_HTML/06_Staff/"],
    sectionIncludedTemplateString: "06_Staff.njk",
    sectionOutputFileName: "06_Staff.html",
    cssFilePath: "../01_CSS/06_Staff",
    cssFilesArray: ["06_Staff"],
  },
  {
    sectionTitle: "Updates section",
    sectionSrcPathArray: ["03_HTML/07_Updates/"],
    sectionIncludedTemplateString: "07_Updates.njk",
    sectionOutputFileName: "07_Updates.html",
    cssFilePath: "../01_CSS/07_Updates",
    cssFilesArray: ["07_Updates"],
  },
  {
    sectionTitle: "Footer section",
    sectionSrcPathArray: ["03_HTML/08_Footer/"],
    sectionIncludedTemplateString: "08_Footer.njk",
    sectionOutputFileName: "08_Footer.html",
    cssFilePath: "../01_CSS/08_Footer",
    cssFilesArray: ["08_Footer"],
  },
];
